#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/03ed0bf9-de5c-41ef-bc63-1904380ac00c 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudLight led;
  CloudTemperatureSensor temperature;
  CloudSchedule schedule;
  bool motordown;
  bool motorup;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include "DHT.h"

#define DHTPIN 18
#define DHTTYPE DHT11

DHT dht(DHTPIN, DHTTYPE);

int motor1pin1 = 26;
int motor1pin2 = 25;


void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  pinMode(motor1pin1, OUTPUT);
  pinMode(motor1pin2, OUTPUT);
  pinMode(14, OUTPUT);
  dht.begin();
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  //DHT_SENSOR_READ();
  if (schedule.isActive()) {
    onMotordownChange();

  } else {
    onMotorupChange(); 
    
  }
 
  
}


/*
  Since Led is READ_WRITE variable, onLedChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLedChange()  {
  // Add your code here to act upon Led change
  if (led == 1){
    digitalWrite(14, HIGH);
  } else{
    digitalWrite(14, LOW);
  }
}

/*
void DHT_SENSOR_READ(){
  float h = dht.readHumidity();
  float t = dht.readTemperature();
  temperature = t;
  humidity = h;
  Serial.print("temp -"); Serial.println(t) ;
  Serial.print("humidity -"); Serial.println(h); 
  delay(1000);
}


*/

/*
  Since Motorup is READ_WRITE variable, onMotorupChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onMotorupChange()  {
  // Add your code here to act upon Motorup change
  digitalWrite(motor1pin1, HIGH);
  digitalWrite(motor1pin2, LOW);  
  delay(2000);
}

/*
  Since Motordown is READ_WRITE variable, onMotordownChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onMotordownChange()  {
  // Add your code here to act upon Motordown change
  digitalWrite(motor1pin1, LOW);
  digitalWrite(motor1pin2, HIGH);  
  delay(2000);
}






/*
  Since Schedule is READ_WRITE variable, onScheduleChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onScheduleChange()  {
  // Add your code here to act upon Schedule change
   
}