// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "746adac6-977a-438c-91c4-68860204385a";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onLedChange();
void onScheduleChange();
void onMotordownChange();
void onMotorupChange();

CloudLight led;
CloudTemperatureSensor temperature;
CloudSchedule schedule;
bool motordown;
bool motorup;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(led, READWRITE, ON_CHANGE, onLedChange);
  ArduinoCloud.addProperty(temperature, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(schedule, READWRITE, ON_CHANGE, onScheduleChange);
  ArduinoCloud.addProperty(motordown, READWRITE, ON_CHANGE, onMotordownChange);
  ArduinoCloud.addProperty(motorup, READWRITE, ON_CHANGE, onMotorupChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
